---
title: "Plotting with `ggplot2`"
author: "My name"
date: "2023-02-12"
output: html_document
---

```{r setup, include = FALSE}
library(tidyverse)
```


## Your first plot


```{r}
library(palmerpenguins)
library(ggplot2)
ggplot(data = penguins) +
  geom_point(mapping = aes(x = bill_length_mm,
                           y = bill_depth_mm,
                           colour = species))
```


## Mapping aesthetics

```{r}
ggplot(penguins) +
  geom_point(aes(x = bill_length_mm,
                 y = bill_depth_mm))
```

## Unmapped parameters

```{r}
ggplot(penguins) +
  geom_point(aes(x = bill_length_mm,
                 y = bill_depth_mm),
             colour = "black")
```

## Try it

- Map the island variable to a shape aesthetics for both dots and linear models
- All dots (circles / triangles / squares) with:
    + A size of 5
    + A transparency of 30% (alpha = 0.7)

```{r}
# write your answer here
```


## Coding mistake

```{r, error = TRUE}
penguins |>
  ggplot() +
  geom_point(aes(x = bill_length_mm, 
                 y = body_mass_g)) +
  geom_smooth(method = "lm")
```


